[project]
name = "tsuzuri-agent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "openai>=3.11.0",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]

[tool.ruff]
target-version = "py312"
line-length = 80

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]
